# Configuration Statique des Utilisateurs (Sauvegarde de Sécurité)

DEFAULT_USERS = [   {   'depot': 'Administration',
        'email': '',
        'nom': 'Bousserouel',
        'pages': "['Profil', 'Admin Centrale', 'Logistique', 'Inventaire', 'Recouvrement', 'RH & Performance']",
        'password': 'admin_imad_pw',
        'prenom': 'Imad',
        'role': 'Admin',
        'username': 'admin_imad',
        'zone': 'Aucune'},
    {   'depot': 'Expédition',
        'email': '',
        'nom': 'AYOUB',
        'pages': "['Logistique', 'Suivi Frigo', 'Inventaire Détail']",
        'password': 'ayoub2026',
        'prenom': 'Ayoub',
        'role': 'Saisie',
        'username': 'Ayoub',
        'zone': 'Aucune'},
    {   'depot': 'Expédition',
        'email': '',
        'nom': 'ISLEM',
        'pages': "['Logistique', 'Suivi Frigo', 'Inventaire Détail']",
        'password': 'islem2026',
        'prenom': 'Islem',
        'role': 'Saisie',
        'username': 'Islem',
        'zone': 'Aucune'},
    {   'depot': 'Préparation',
        'email': '',
        'nom': 'SEIF',
        'pages': "['Inventaire', 'Inventaire Détail']",
        'password': 'seif2026',
        'prenom': 'Seif',
        'role': 'Saisie',
        'username': 'Seif',
        'zone': 'Aucune'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'Berghout',
        'pages': "['Inventaire Détail']",
        'password': 'idris',
        'prenom': 'Idris',
        'role': 'Saisie',
        'username': 'idris',
        'zone': 'C'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'Lefkir',
        'pages': "['Inventaire Détail']",
        'password': 'aymen123',
        'prenom': 'Aymen',
        'role': 'Saisie',
        'username': 'aymen',
        'zone': 'A'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'Kadouch',
        'pages': "['Inventaire Détail']",
        'password': 'khero123',
        'prenom': 'Khireddine',
        'role': 'Saisie',
        'username': 'khero',
        'zone': 'A'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'Rabah',
        'pages': "['Inventaire Détail']",
        'password': 'rabeh123',
        'prenom': 'Rabah',
        'role': 'Saisie',
        'username': 'rabeh',
        'zone': 'B'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'Eli Adj Moual',
        'pages': "['Inventaire Détail']",
        'password': 'yacine123',
        'prenom': 'Yacine',
        'role': 'Saisie',
        'username': 'yacine',
        'zone': 'B'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'Belheddad',
        'pages': "['Inventaire Détail']",
        'password': 'aek123',
        'prenom': 'Abdelkader',
        'role': 'Saisie',
        'username': 'aek',
        'zone': 'D'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'Koulai',
        'pages': "['Inventaire Détail']",
        'password': 'aymen123',
        'prenom': 'Aymen',
        'role': 'Saisie',
        'username': 'aymenk',
        'zone': 'D'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'Ouali',
        'pages': "['Inventaire Détail']",
        'password': 'mustapha123',
        'prenom': 'Mustapha',
        'role': 'Saisie',
        'username': 'mustapha',
        'zone': 'C'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'RAMI',
        'pages': "['Inventaire Détail', 'Inventaire Triple']",
        'password': 'rami123',
        'prenom': 'Rami',
        'role': 'Superviseur',
        'username': 'rami',
        'zone': 'Aucune'},
    {   'depot': 'Expédition',
        'email': '',
        'nom': 'Benmesrouk',
        'pages': "['Dashboard', 'Suivi Frigo']",
        'password': 'karim123',
        'prenom': 'Karim',
        'role': 'Superviseur',
        'username': 'karim',
        'zone': 'Aucune'}]
