# Configuration Statique des Utilisateurs (Sauvegarde de Sécurité)

DEFAULT_USERS = [   {   'depot': 'Administration',
        'email': '',
        'nom': 'Bousserouel',
        'pages': "['Profil', 'Admin Centrale', 'Logistique', 'Inventaire', 'Recouvrement', 'RH & Performance']",
        'password': 'admin_imad_pw',
        'prenom': 'Imad',
        'role': 'Admin',
        'username': 'admin_imad',
        'zone': 'Aucune'},
    {   'depot': 'Expédition',
        'email': '',
        'nom': '',
        'pages': "['Logistique', 'Suivi Frigo', 'Inventaire Détail']",
        'password': 'ayoub2026',
        'prenom': 'Ayoub',
        'role': 'Saisie',
        'username': 'Ayoub',
        'zone': 'Aucune'},
    {   'depot': 'Expédition',
        'email': '',
        'nom': '',
        'pages': "['Logistique', 'Suivi Frigo', 'Inventaire Détail']",
        'password': 'islem2026',
        'prenom': 'Islem',
        'role': 'Saisie',
        'username': 'Islem',
        'zone': 'Aucune'},
    {   'depot': 'Préparation',
        'email': '',
        'nom': '',
        'pages': "['Inventaire', 'Inventaire Détail']",
        'password': 'seif2026',
        'prenom': 'Seif',
        'role': 'Saisie',
        'username': 'Seif',
        'zone': 'Aucune'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'BERGHOUT',
        'pages': "['Inventaire Détail']",
        'password': 'idris',
        'prenom': 'IDRIS',
        'role': 'Saisie',
        'username': 'idris',
        'zone': 'C'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'LEFKIR',
        'pages': "['Inventaire Détail']",
        'password': 'aymen123',
        'prenom': 'AYMEN',
        'role': 'Saisie',
        'username': 'aymen',
        'zone': 'A'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'KADOUCH',
        'pages': "['Inventaire Détail']",
        'password': 'khero123',
        'prenom': 'KHIREDDINE',
        'role': 'Saisie',
        'username': 'khero',
        'zone': 'A'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'EN ATTENTE',
        'pages': "['Inventaire Détail']",
        'password': 'rabeh123',
        'prenom': 'RABAH',
        'role': 'Saisie',
        'username': 'rabeh',
        'zone': 'B'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'ELI ADJ MOUAL',
        'pages': "['Inventaire Détail']",
        'password': 'yacine123',
        'prenom': 'YACINE',
        'role': 'Saisie',
        'username': 'yacine',
        'zone': 'B'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'belheddad',
        'pages': "['Inventaire Détail']",
        'password': 'aek123',
        'prenom': 'abdelkader',
        'role': 'Saisie',
        'username': 'aek',
        'zone': 'D'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'koulai',
        'pages': "['Inventaire Détail']",
        'password': 'aymen123',
        'prenom': 'aymen',
        'role': 'Saisie',
        'username': 'aymenk',
        'zone': 'D'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'ouali',
        'pages': "['Inventaire Détail']",
        'password': 'mustapha123',
        'prenom': 'mustapha',
        'role': 'Saisie',
        'username': 'mustapha',
        'zone': 'C'},
    {   'depot': 'Stock',
        'email': '',
        'nom': 'rami',
        'pages': "['Inventaire Détail', 'Inventaire Triple']",
        'password': 'rami123',
        'prenom': '',
        'role': 'Superviseur',
        'username': 'rami',
        'zone': 'Aucune'},
    {   'depot': 'Expédition',
        'email': '',
        'nom': 'benmesrouk',
        'pages': "['Dashboard', 'Suivi Frigo']",
        'password': 'karim123',
        'prenom': 'karim',
        'role': 'Superviseur',
        'username': 'karim',
        'zone': 'Aucune'}]
