services:
  - type: web
    name: pharmaciel-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: pharmaciel-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
