import pandas as pd
import os

data = [
    {
        "reference": "26/RC0000000144",
        "type": "",
        "date": "30-04-26",
        "code_client": "0130",
        "client": "DEKOUKA FAIZA - HOURIA BAAZIZI",
        "region": "TIPAZA",
        "produit": "APTAMIL PEPTI JUNIOR LAIT EN POUDRE",
        "statut_bon": "Cloturer",
        "motif": "RETOUR",
        "lot": "2027.01.18",
        "prix_vente": 1070.98,
        "ppa": 1285.18,
        "date_exp": "01-01-27",
        "quantite": 4,
        "tx_vente": 0.00,
        "valeur_vente": 4283.92,
        "statut": "RETOUR RAPPEL DE LOT",
        "remarque_ligne": "rappel de lot",
        "cree_par": "SOUHILA",
        "date_creation": "30-04-26 15:10:45",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "05-05-26 11:21:22",
        "cloturer_par": "AMINE",
        "cout_revient": 4107.32,
        "ref_facture": "26/BL001970",
        "date_facture": "26-02-26",
        "categorie": "COM",
        "facture_creee_par": "SOUHILA",
        "zone_produit": "D",
        "preparateur": "Idris",
        "verif_1": "Karim",
        "reponse": "ot",
        "emp_produit": "D-06-E1",
        "responsable": "Depot",
        "avis_dt": "Avis favorable",
        "verifier_par": "Amine",
        "envoyer_par": "Karim",
        "recu_par": "Amine",
        "date_verification": "02-05-26",
        "date_envoi": "03-05-26",
        "date_reception": "04-05-26",
        "nbr_jours": 63,
        "offre": "",
        "delai_reclam": 5.00
    },
    {
        "reference": "26/RC0000000146",
        "type": "",
        "date": "30-04-26",
        "code_client": "0164",
        "client": "DZANOUNI MOHAMED",
        "region": "ALGER 1",
        "produit": "TROMBIX COMP. PELLI. 20MG B/30",
        "statut_bon": "Cloturer",
        "motif": "RAPPEL DE LOT",
        "lot": "029325",
        "prix_vente": 5550.93,
        "ppa": 6661.12,
        "date_exp": "01-03-28",
        "quantite": 3,
        "tx_vente": 20.00,
        "valeur_vente": 13877.33,
        "statut": "EN COURS",
        "remarque_ligne": "",
        "cree_par": "ZINOU",
        "date_creation": "30-04-26 15:41:52",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Oui",
        "date_cloture": "03-05-26 11:22:10",
        "cloturer_par": "AMINE",
        "cout_revient": 11971.68,
        "ref_facture": "26/BL001094",
        "date_facture": "04-02-26",
        "categorie": "COM",
        "facture_creee_par": "ZINOU",
        "zone_produit": "C",
        "preparateur": "Aymen",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "A-07-E1",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 85,
        "offre": "",
        "delai_reclam": 3.00
    },
    {
        "reference": "26/RC0000000146",
        "type": "",
        "date": "30-04-26",
        "code_client": "0164",
        "client": "DZANOUNI MOHAMED",
        "region": "ALGER 1",
        "produit": "TROMBIX COMP. PELLI. 15MG B/30",
        "statut_bon": "Cloturer",
        "motif": "RAPPEL DE LOT",
        "lot": "007825",
        "prix_vente": 5550.93,
        "ppa": 6661.12,
        "date_exp": "01-03-28",
        "quantite": 3,
        "tx_vente": 20.00,
        "valeur_vente": 13877.33,
        "statut": "EN COURS",
        "remarque_ligne": "",
        "cree_par": "ZINOU",
        "date_creation": "30-04-26 15:41:52",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Oui",
        "date_cloture": "03-05-26 11:22:10",
        "cloturer_par": "AMINE",
        "cout_revient": 11970.57,
        "ref_facture": "26/BL001094",
        "date_facture": "04-02-26",
        "categorie": "COM",
        "facture_creee_par": "ZINOU",
        "zone_produit": "D",
        "preparateur": "Aymen",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "1.A01.2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 85,
        "offre": "",
        "delai_reclam": 3.00
    },
    {
        "reference": "26/RC0000000002",
        "type": "",
        "date": "04-01-26",
        "code_client": "1102",
        "client": "KHETTAR FOUZIA",
        "region": "ALGER 1",
        "produit": "LEXIN 1G SACHET B/12",
        "statut_bon": "Cloturer",
        "motif": "ERREUR COMMERCIAL",
        "lot": "8526",
        "prix_vente": 541.06,
        "ppa": 649.27,
        "date_exp": "01-06-28",
        "quantite": 11,
        "tx_vente": 10.00,
        "valeur_vente": 5410.60,
        "statut": "ACCEPTE",
        "remarque_ligne": "VOLU CP AU LIEU",
        "cree_par": "DJIHAD",
        "date_creation": "04-01-26 12:32:29",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "07-01-26 14:55:19",
        "cloturer_par": "AMINE",
        "cout_revient": 4925.03,
        "ref_facture": "25/BL006888",
        "date_facture": "24-12-25",
        "categorie": "COM",
        "facture_creee_par": "ASMA",
        "zone_produit": "D",
        "preparateur": "Kheiro",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "C-02-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 11,
        "offre": "",
        "delai_reclam": 3.00
    },
    {
        "reference": "26/RC0000000004",
        "type": "",
        "date": "07-01-26",
        "code_client": "0396",
        "client": "TARFAOUI MOUNA",
        "region": "CHLEF",
        "produit": "LEXIN 1G SACHET B/12",
        "statut_bon": "Cloturer",
        "motif": "ERREUR COMMERCIAL",
        "lot": "8526",
        "prix_vente": 541.06,
        "ppa": 649.27,
        "date_exp": "01-06-28",
        "quantite": 22,
        "tx_vente": 10.00,
        "valeur_vente": 10821.20,
        "statut": "ACCEPTE",
        "remarque_ligne": "cp ou lieu sht",
        "cree_par": "ICHRAK",
        "date_creation": "07-01-26 11:39:15",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "29-01-26 07:15:30",
        "cloturer_par": "AMINE",
        "cout_revient": 9850.06,
        "ref_facture": "26/BL000075",
        "date_facture": "05-01-26",
        "categorie": "COM",
        "facture_creee_par": "ICHRAK",
        "zone_produit": "D",
        "preparateur": "Rabeh",
        "verif_1": "",
        "reponse": "ot, recu 12",
        "emp_produit": "C-02-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 2,
        "offre": "",
        "delai_reclam": 22.00
    },
    {
        "reference": "26/RC0000000004",
        "type": "",
        "date": "07-01-26",
        "code_client": "0396",
        "client": "TARFAOUI MOUNA",
        "region": "CHLEF",
        "produit": "CIPROFLOXACINE BEKER 750MG COMP. PELL",
        "statut_bon": "Cloturer",
        "motif": "ERREUR COMMERCIAL",
        "lot": "082024",
        "prix_vente": 872.90,
        "ppa": 1047.50,
        "date_exp": "01-07-27",
        "quantite": 15,
        "tx_vente": 0.00,
        "valeur_vente": 8729.00,
        "statut": "ACCEPTE",
        "remarque_ligne": "cp ou lieu sht",
        "cree_par": "ICHRAK",
        "date_creation": "07-01-26 11:39:15",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "29-01-26 07:15:30",
        "cloturer_par": "AMINE",
        "cout_revient": 7274.10,
        "ref_facture": "26/BL000075",
        "date_facture": "05-01-26",
        "categorie": "COM",
        "facture_creee_par": "ICHRAK",
        "zone_produit": "B",
        "preparateur": "Rabeh",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "1.A01.1",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 2,
        "offre": "",
        "delai_reclam": 22.00
    },
    {
        "reference": "26/RC0000000009",
        "type": "",
        "date": "19-01-26",
        "code_client": "0469",
        "client": "TALANERIHANE MOHAMED RAFIK",
        "region": "ALGER EST",
        "produit": "DOLYC COMP. 500MG B/20",
        "statut_bon": "Cloturer",
        "motif": "ERREUR DU PHARMACIEN",
        "lot": "25012",
        "prix_vente": 80.00,
        "ppa": 120.00,
        "date_exp": "30-06-26",
        "quantite": 100,
        "tx_vente": 80.00,
        "valeur_vente": 4444.44,
        "statut": "ACCEPTE",
        "remarque_ligne": "errur dosage 1g ou bien",
        "cree_par": "ICHRAK",
        "date_creation": "19-01-26 14:35:06",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "03-02-26 16:22:43",
        "cloturer_par": "AMINE",
        "cout_revient": 4222.00,
        "ref_facture": "26/BL000331",
        "date_facture": "13-01-26",
        "categorie": "COM",
        "facture_creee_par": "ICHRAK",
        "zone_produit": "A",
        "preparateur": "Yacine",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "B-06-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 6,
        "offre": "",
        "delai_reclam": 15.00
    },
    {
        "reference": "26/RC0000000010",
        "type": "",
        "date": "19-01-26",
        "code_client": "0070",
        "client": "AIDJA FAIZA NADJET",
        "region": "BLIDA",
        "produit": "DOLYC COMP. 500MG B/20",
        "statut_bon": "Cloturer",
        "motif": "ERREUR DU PHARMACIEN",
        "lot": "25012",
        "prix_vente": 80.00,
        "ppa": 120.00,
        "date_exp": "30-06-26",
        "quantite": 1,
        "tx_vente": 80.00,
        "valeur_vente": 44.44,
        "statut": "ACCEPTE",
        "remarque_ligne": "",
        "cree_par": "ASMA",
        "date_creation": "19-01-26 16:42:18",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "07-02-26 09:19:27",
        "cloturer_par": "AMINE",
        "cout_revient": 42.22,
        "ref_facture": "26/BL000407",
        "date_facture": "15-01-26",
        "categorie": "COM",
        "facture_creee_par": "ASMA",
        "zone_produit": "A",
        "preparateur": "Aek",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "B-06-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 4,
        "offre": "",
        "delai_reclam": 19.00
    },
    {
        "reference": "26/RC0000000016",
        "type": "",
        "date": "29-01-26",
        "code_client": "C0077",
        "client": "GHERISSI BOUCHRA EPS SAIDI",
        "region": "ALGER 1",
        "produit": "EXFORGE 10MG/160MG B/28 COMP",
        "statut_bon": "Cloturer",
        "motif": "ERREUR DU PHARMACIEN",
        "lot": "BC0006",
        "prix_vente": 1164.58,
        "ppa": 1397.50,
        "date_exp": "01-01-28",
        "quantite": 10,
        "tx_vente": 0.00,
        "valeur_vente": 11645.80,
        "statut": "ACCEPTE",
        "remarque_ligne": "BESION 5/160",
        "cree_par": "SOUHILA",
        "date_creation": "29-01-26 09:54:46",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "03-02-26 16:25:18",
        "cloturer_par": "AMINE",
        "cout_revient": 9739.70,
        "ref_facture": "26/BL000840",
        "date_facture": "28-01-26",
        "categorie": "EPH",
        "facture_creee_par": "SOUHILA",
        "zone_produit": "A",
        "preparateur": "Mustapha",
        "verif_1": "",
        "reponse": "POT",
        "emp_produit": "D-07-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 1,
        "offre": "",
        "delai_reclam": 5.00
    },
    {
        "reference": "26/RC0000000028",
        "type": "",
        "date": "08-02-26",
        "code_client": "C0051",
        "client": "NADJEM BOUALEM",
        "region": "ALGER 2",
        "produit": "VITADONE VIT D3 200 000UI AMP BUV",
        "statut_bon": "Cloturer",
        "motif": "RETOUR",
        "lot": "AA422",
        "prix_vente": 216.67,
        "ppa": 260.00,
        "date_exp": "01-06-28",
        "quantite": 14,
        "tx_vente": 0.00,
        "valeur_vente": 2166.70,
        "statut": "ACCEPTE",
        "remarque_ligne": "",
        "cree_par": "SOUHILA",
        "date_creation": "08-02-26 11:20:22",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "15-02-26 10:34:59",
        "cloturer_par": "AMINE",
        "cout_revient": 2022.30,
        "ref_facture": "26/BL001185",
        "date_facture": "05-02-26",
        "categorie": "COM",
        "facture_creee_par": "SOUHILA",
        "zone_produit": "A",
        "preparateur": "Idris",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "D-07-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 3,
        "offre": "",
        "delai_reclam": 7.00
    },
    {
        "reference": "26/RC0000000027",
        "type": "",
        "date": "11-02-26",
        "code_client": "0421",
        "client": "ABADA SIHAM",
        "region": "ALGER 2",
        "produit": "URICARE 3G B/1 SACHET DOSE",
        "statut_bon": "Cloturer",
        "motif": "PNC (PRODUIT ABIME)",
        "lot": "7712535",
        "prix_vente": 623.81,
        "ppa": 748.57,
        "date_exp": "01-03-27",
        "quantite": 1,
        "tx_vente": 0.00,
        "valeur_vente": 519.84,
        "statut": "ACCEPTE",
        "remarque_ligne": "la poudre cristalise",
        "cree_par": "SAFA",
        "date_creation": "11-02-26 10:04:43",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "15-02-26 10:57:07",
        "cloturer_par": "AMINE",
        "cout_revient": 415.87,
        "ref_facture": "26/BL001091",
        "date_facture": "03-02-26",
        "categorie": "PA",
        "facture_creee_par": "SAFA",
        "zone_produit": "A",
        "preparateur": "Aymen",
        "verif_1": "",
        "reponse": "ote",
        "emp_produit": "1.A01.2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 8,
        "offre": "",
        "delai_reclam": 4.00
    },
    {
        "reference": "26/RC0000000032",
        "type": "",
        "date": "18-02-26",
        "code_client": "1156",
        "client": "CHAMOUNI LYLIA DORIA",
        "region": "ALGER EST",
        "produit": "OXOMEMAZINE KPMA 1MG/ML SIRO",
        "statut_bon": "Cloturer",
        "motif": "ERREUR DU PHARMACIEN",
        "lot": "38509",
        "prix_vente": 102.36,
        "ppa": 136.13,
        "date_exp": "01-07-27",
        "quantite": 5,
        "tx_vente": 10.00,
        "valeur_vente": 465.27,
        "statut": "ACCEPTE",
        "remarque_ligne": "",
        "cree_par": "SAMIR",
        "date_creation": "18-02-26 15:11:22",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "22-02-26 09:31:20",
        "cloturer_par": "AMINE",
        "cout_revient": 393.70,
        "ref_facture": "26/BL001617",
        "date_facture": "16-02-26",
        "categorie": "EPH",
        "facture_creee_par": "SAMIR",
        "zone_produit": "B",
        "preparateur": "Aek",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "D-01-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 2,
        "offre": "",
        "delai_reclam": 4.00
    },
    {
        "reference": "26/RC0000000036",
        "type": "",
        "date": "24-02-26",
        "code_client": "1083",
        "client": "DJERIR KHEIREDDINE",
        "region": "ALGER EST",
        "produit": "DESLOR 5MG COMP B/30",
        "statut_bon": "Cloturer",
        "motif": "ERREUR COMMERCIAL",
        "lot": "5116",
        "prix_vente": 704.00,
        "ppa": 844.80,
        "date_exp": "01-02-28",
        "quantite": 15,
        "tx_vente": 50.00,
        "valeur_vente": 10560.00,
        "statut": "EN COURS",
        "remarque_ligne": "",
        "cree_par": "ZINOU",
        "date_creation": "24-02-26 12:37:20",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "02-03-26 09:07:56",
        "cloturer_par": "AMINE",
        "cout_revient": 6211.80,
        "ref_facture": "26/BL001782",
        "date_facture": "21-02-26",
        "categorie": "COM",
        "facture_creee_par": "ZINOU",
        "zone_produit": "B",
        "preparateur": "Rabeh",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "C-03-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 3,
        "offre": "",
        "delai_reclam": 6.00
    },
    {
        "reference": "26/RC0000000038",
        "type": "",
        "date": "02-03-26",
        "code_client": "C0048",
        "client": "NAIMI SOUAD EPS REBIHI",
        "region": "BLIDA",
        "produit": "BIOVEX ADULTE 500MG/ 200MG/ 25MG B/08",
        "statut_bon": "Cloturer",
        "motif": "PNC (PRODUIT ABIME)",
        "lot": "63425282",
        "prix_vente": 273.49,
        "ppa": 328.19,
        "date_exp": "01-10-27",
        "quantite": 5,
        "tx_vente": 0.00,
        "valeur_vente": 1367.45,
        "statut": "ACCEPTE",
        "remarque_ligne": "",
        "cree_par": "SOUHILA",
        "date_creation": "02-03-26 09:34:21",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "04-03-26 09:12:21",
        "cloturer_par": "AMINE",
        "cout_revient": 1139.55,
        "ref_facture": "26/BL002015",
        "date_facture": "01-03-26",
        "categorie": "PA",
        "facture_creee_par": "SOUHILA",
        "zone_produit": "C",
        "preparateur": "Idris",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "D-05-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 1,
        "offre": "",
        "delai_reclam": 2.00
    },
    {
        "reference": "26/RC0000000040",
        "type": "",
        "date": "03-03-26",
        "code_client": "C0051",
        "client": "NADJEM BOUALEM",
        "region": "ALGER 2",
        "produit": "APROVASC COMP.PELL. 150MG/10MG B/30",
        "statut_bon": "Cloturer",
        "motif": "ERREUR DU PHARMACIEN",
        "lot": "DNN0981",
        "prix_vente": 1247.92,
        "ppa": 1497.50,
        "date_exp": "01-11-26",
        "quantite": 10,
        "tx_vente": 0.00,
        "valeur_vente": 12479.20,
        "statut": "ACCEPTE",
        "remarque_ligne": "5/150",
        "cree_par": "SOUHILA",
        "date_creation": "03-03-26 11:02:23",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "08-03-26 08:56:56",
        "cloturer_par": "AMINE",
        "cout_revient": 11344.70,
        "ref_facture": "26/BL001437",
        "date_facture": "12-02-26",
        "categorie": "EPH",
        "facture_creee_par": "SOUHILA",
        "zone_produit": "A",
        "preparateur": "Mustapha",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "A-07-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 19,
        "offre": "",
        "delai_reclam": 5.00
    },
    {
        "reference": "26/RC0000000043",
        "type": "",
        "date": "04-03-26",
        "code_client": "0412",
        "client": "CHAACHOUA AMEL",
        "region": "AIN DEFLA",
        "produit": "ATORIN BEKER 20MG COMP PEL B/30",
        "statut_bon": "Cloturer",
        "motif": "ERREUR COMMERCIAL",
        "lot": "104325",
        "prix_vente": 1037.41,
        "ppa": 1244.90,
        "date_exp": "01-09-27",
        "quantite": 3,
        "tx_vente": 0.00,
        "valeur_vente": 1556.12,
        "statut": "ACCEPTE",
        "remarque_ligne": "",
        "cree_par": "ICHRAK",
        "date_creation": "04-03-26 10:46:16",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "11-03-26 09:15:58",
        "cloturer_par": "AMINE",
        "cout_revient": 1197.00,
        "ref_facture": "26/BL002090",
        "date_facture": "02-03-26",
        "categorie": "COM",
        "facture_creee_par": "ICHRAK",
        "zone_produit": "A",
        "preparateur": "Yacine",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "D-01-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 2,
        "offre": "",
        "delai_reclam": 7.00
    },
    {
        "reference": "26/RC0000000043",
        "type": "",
        "date": "04-03-26",
        "code_client": "0412",
        "client": "CHAACHOUA AMEL",
        "region": "AIN DEFLA",
        "produit": "IRYS 4MG COMP. PELL. SEC B/30",
        "statut_bon": "Cloturer",
        "motif": "ERREUR COMMERCIAL",
        "lot": "5276",
        "prix_vente": 622.91,
        "ppa": 747.50,
        "date_exp": "01-05-28",
        "quantite": 5,
        "tx_vente": 30.00,
        "valeur_vente": 2395.81,
        "statut": "ACCEPTE",
        "remarque_ligne": "erreur de saisie 2 fois",
        "cree_par": "ICHRAK",
        "date_creation": "04-03-26 10:46:16",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "11-03-26 09:15:58",
        "cloturer_par": "AMINE",
        "cout_revient": 1483.10,
        "ref_facture": "26/BL002090",
        "date_facture": "02-03-26",
        "categorie": "COM",
        "facture_creee_par": "ICHRAK",
        "zone_produit": "D",
        "preparateur": "Yacine",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "D-01-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 2,
        "offre": "",
        "delai_reclam": 7.00
    },
    {
        "reference": "26/RC0000000042",
        "type": "",
        "date": "04-03-26",
        "code_client": "1185",
        "client": "DJEDDI LAMIA",
        "region": "ALGER 2",
        "produit": "TROPIRUS 18UG PDR INH B/30 GELL 18 ug",
        "statut_bon": "Cloturer",
        "motif": "ERREUR COMMERCIAL",
        "lot": "2545014B",
        "prix_vente": 1683.75,
        "ppa": 2020.50,
        "date_exp": "01-01-27",
        "quantite": 3,
        "tx_vente": 0.00,
        "valeur_vente": 5051.25,
        "statut": "ACCEPTE",
        "remarque_ligne": "",
        "cree_par": "AMINA",
        "date_creation": "04-03-26 11:26:12",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "08-03-26 09:01:08",
        "cloturer_par": "AMINE",
        "cout_revient": 4592.04,
        "ref_facture": "26/BL001588",
        "date_facture": "16-02-26",
        "categorie": "COM",
        "facture_creee_par": "AMINA",
        "zone_produit": "C",
        "preparateur": "Idris",
        "verif_1": "",
        "reponse": "ot",
        "emp_produit": "D-01-E2",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 16,
        "offre": "",
        "delai_reclam": 4.00
    },
    {
        "reference": "26/RC0000000050",
        "type": "",
        "date": "15-03-26",
        "code_client": "1163",
        "client": "YEDDOU AMINA",
        "region": "ALGER 2",
        "produit": "BIORAPID INSULINE 100UI/ML B/5 SOL.INJ",
        "statut_bon": "Cloturer",
        "motif": "ERREUR DE DEPOT (MANQUE)",
        "lot": "005525065",
        "prix_vente": 3355.00,
        "ppa": 4026.00,
        "date_exp": "01-10-27",
        "quantite": 10,
        "tx_vente": 30.00,
        "valeur_vente": 27958.33,
        "statut": "REFUSE",
        "remarque_ligne": "facturé 50 reçu 40",
        "cree_par": "AMINA",
        "date_creation": "15-03-26 09:42:52",
        "psycho": "Non",
        "frigo": "Oui",
        "chere": "Non",
        "date_cloture": "15-03-26 10:15:06",
        "cloturer_par": "AMINE",
        "cout_revient": 23964.30,
        "ref_facture": "26/BL002464",
        "date_facture": "12-03-26",
        "categorie": "COM",
        "facture_creee_par": "AMINA",
        "zone_produit": "FRIGO",
        "preparateur": "Idris",
        "verif_1": "",
        "reponse": "LA CAMERA",
        "emp_produit": "CHAMBRE FROIDE",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 3,
        "offre": "",
        "delai_reclam": 3.00
    },
    {
        "reference": "26/RC0000000057",
        "type": "",
        "date": "15-03-26",
        "code_client": "1217",
        "client": "FOUAL FAHIMA",
        "region": "ALGER 2",
        "produit": "APTAMIL PEPTI JUNIOR LAIT EN POUDRE",
        "statut_bon": "Cloturer",
        "motif": "RETOUR",
        "lot": "2027.01.18",
        "prix_vente": 1070.98,
        "ppa": 1285.18,
        "date_exp": "01-01-27",
        "quantite": 10,
        "tx_vente": 0.00,
        "valeur_vente": 10709.80,
        "statut": "ACCEPTE",
        "remarque_ligne": "rappel de lot",
        "cree_par": "AMINA",
        "date_creation": "15-03-26 12:31:55",
        "psycho": "Non",
        "frigo": "Non",
        "chere": "Non",
        "date_cloture": "23-03-26 09:08:04",
        "cloturer_par": "AMINE",
        "cout_revient": 10268.30,
        "ref_facture": "26/BL001831",
        "date_facture": "22-02-26",
        "categorie": "D",
        "facture_creee_par": "AMINA",
        "zone_produit": "D",
        "preparateur": "Kheiro",
        "verif_1": "",
        "reponse": "POT",
        "emp_produit": "D-06-E1",
        "responsable": "",
        "avis_dt": "",
        "verifier_par": "",
        "envoyer_par": "",
        "recu_par": "",
        "date_verification": "",
        "date_envoi": "",
        "date_reception": "",
        "nbr_jours": 21,
        "offre": "",
        "delai_reclam": 8.00
    }
]

df = pd.DataFrame(data)
os.makedirs("data", exist_ok=True)
df.to_csv("data/db_reclamations_analyse.csv", index=False, encoding="utf-8-sig")
print("Successfully generated data/db_reclamations_analyse.csv with 20 rows.")
