[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 10

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1877f2"
backgroundColor = "#f0f2f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1c21"
font = "sans serif"
